### ISSUE TITLE
Side-by-Side images

### ISSUE THREAD

**Issue by evanmalmud** [Roslovets-Inc/ckeditor5-build-strapi-wysiwyg#12]
You can workaround this one with the HTML editor I think, but i'm having trouble getting it to work.

I put in - 

```
<div class="container image">
  <div class="row">
    <div class="col-6">
      <img style="height: auto; max-width:100%;" src="IMAGE2">
    </div>
    <div class="col-6">
      <img style="height: auto; max-width:100%;" src="IMAGE1">
    </div>
</div>
```

And in the editor it looks good, but ultimately on my page they end up stacked. 
Unsure why. Might be my css but I can't figure it out.

The fact that this works almost 100% verify's its my css on the site - https://www.codeply.com/go/bp/IAq8t3KYUN

**Comment by roslovets** [comment]
I'm not sure it's still relevant. Especially after upgrade of Strapi and CKEditor.
