### ISSUE TITLE
Lack of RemoveFormat

### ISSUE THREAD

**Issue by Pb600** [Roslovets-Inc/ckeditor5-build-strapi-wysiwyg#14]
Would be really usefull to have RemoveFormat plugin available, as otherwise the editor will maintain the previous line formatting when pressing enter and you will struggle to change back to default.

**Comment by roslovets** [comment]
Introduced in [v1.12.0](https://github.com/Roslovets-Inc/ckeditor5-build-strapi-wysiwyg/releases/tag/v1.12.0)
