### ISSUE TITLE
Source editing support for CKEditor 5 

### ISSUE THREAD

**Issue by elitonfreitas** [Roslovets-Inc/ckeditor5-build-strapi-wysiwyg#18]
Congratulations on the excellent work.
You might consider including the @ckeditor/ckeditor5-source-editing plugin. It's a very relevant feature for some users.

**Comment by soduno** [comment]
I would gladly request it too. And thank you so much for creating this nice integration with strapi and ckeditor :)

**Comment by AlexZCP** [comment]
Please add source support editing - its very useful!
Thank you much!

**Comment by hkashlan** [comment]
I created a PR to add the source editing feature

**Comment by roslovets** [comment]
> I created a PR to add the source editing feature

Please fix broken Media Library button in CKEditor v29.0.0: https://github.com/Roslovets-Inc/ckeditor5-build-strapi-wysiwyg/pull/20#issuecomment-967754318

After this I will be able to introduce Source editing feature.

**Comment by roslovets** [comment]
Thank you, folks. sourceEditing is implemented in [v2.1.0](https://github.com/Roslovets-Inc/ckeditor5-build-strapi-wysiwyg/releases/tag/v2.1.0)
