### ISSUE TITLE
Already supporting Strapi 4 ?

### ISSUE THREAD

**Issue by marco-villanueva** [Roslovets-Inc/ckeditor5-build-strapi-wysiwyg#24]
A few days ago they released the stable version of Strapi 4, but the folder structure has changed. Will there be any update of the library for this version?

**Comment by roslovets** [comment]
Thanks for the information, working on that...

**Comment by Hedg0305** [comment]
Any idea on when it's going to be finished?

**Comment by marco-villanueva** [comment]
> 

Check the implementation of colton75, is a temporary solutión and it works for me
https://github.com/Roslovets-Inc/strapi-plugin-ckeditor5/issues/33
