### ISSUE TITLE
MediaLib plugin yields error "Properly integrate editor into Strapi to make button work"

### ISSUE THREAD

**Issue by spamsch** [Roslovets-Inc/ckeditor5-build-strapi-wysiwyg#25]
I do not find any documentation on how to configure config.onToggle. It seems to be a function but what should the content be?

**Comment by roslovets** [comment]
You are integrating CKEditor to Strapi CMS, right?
If so, use this plugin: https://github.com/Roslovets-Inc/strapi-plugin-ckeditor5
It will deliver CKEditor to you with working MediaLib button (note: currently works with Strapi v3).

**Comment by spamsch** [comment]
Uh ok - why are there two plugins with almost the same name? Will try it out!

**Comment by roslovets** [comment]
> Uh ok - why are there two plugins with almost the same name? Will try it out!

Current repo is just a special CKEditor build for plugin. It should be separated from plugin itself because of technical staff.
