### ISSUE TITLE
Extra/extend image alignments

### ISSUE THREAD

**Issue by peopledrivemecrazy** [Roslovets-Inc/ckeditor5-build-strapi-wysiwyg#3]
![image](https://user-images.githubusercontent.com/3922469/106239555-d5cb0c80-6228-11eb-8a14-8e2f6e52e338.png)

Please add this feature [ckeditor5 docs](https://ckeditor.com/docs/ckeditor5/latest/features/image.html#using-pixels-instead-of-percentage-width)

I really want left/right aligned images to the content.

**Comment by roslovets** [comment]
Done in v1.2.1. Thank you for good proposition!
